name: Upload XC_GUI component

on:
  push:
    tags:
      - "v*"

jobs:
  upload_component:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload XC_GUI to ESP Component Registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "xc_gui: ."
          namespace: "gigasitron"